import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adwise Technology",
  description: "Generated by Adwise Team",
};

export default function RootLayout({
  children,
}:   Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body className={`${geistSans.variable} ${geistMono.variable}`>  
       {children} 
     
        <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-Q3R9PBHJYT"
        strategy="afterInteractive"
      />

      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-Q3R9PBHJYT');
        `}
      </Script>
      </body>
    </html>
  );
}
